name: Develop Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3


    # Push images to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build container image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:develop-${{ github.run_id }} .

    # Run container
    - name: Run Docker Container
      run: |
        docker run -d --name test-container -p 8081:80 ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

    # Test website accessibility
    - name: Test Container
      run: curl -I localhost:8081

    - name: Push Docker Images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:develop-${{ github.run_id }}

    # Cleanup
    - name: Cleanup
      run: docker rm -f test-container
