name: Develop Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: demo

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3


    # Push images to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    # Build container image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.USERNAME }}/nginx-application:latest .
        docker build -t ${{ secrets.USERNAME }}/nginx-application:develop-${{ github.run_id }} .

    # Run container
    - name: Run Docker Container
      run: |
        docker run -d --name test-container -p 8081:80 ${{ secrets.USERNAME }}/nginx-application:latest

    # Test website accessibility
   # - name: Test Container


    - name: Push Docker Images
      run: |
        docker push ${{ secrets.USERNAME }}/nginx-application:latest
        docker push ${{ secrets.USERNAME }}/nginx-application:develop-${{ github.run_id }}

    # Cleanup
    - name: Cleanup
      run: docker rm -f test-container
